/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import UserProfile from './UserProfile';
import NutrientCards from './NutrientCards';
import MealCards from './MealCards';
import TodaysDetails from './TodaysDetails';

interface MainContentProps {}

const MainContent: React.FC<MainContentProps> = () => {
  return (
    <main className="flex flex-col ml-5 w-[61%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col pt-5 w-full min-h-[933px] max-md:mt-8 max-md:max-w-full max-sm:hidden">
        <UserProfile />
        <NutrientCards />
        <MealCards />
        <TodaysDetails />
      </div>
    </main>
  );
};

export default MainContent;