/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface MealCardProps {
  imageSrc: string;
  location: string;
  mealName: string;
  calories: number;
}

const MealCard: React.FC<MealCardProps> = ({ imageSrc, location, mealName, calories }) => (
  <div className="flex flex-col flex-1 shrink justify-center self-stretch p-3 my-auto bg-white rounded-3xl shadow-2xl basis-[42px] min-h-[211px] max-sm:hidden">
    <img loading="lazy" src={imageSrc} alt={mealName} className="object-contain rounded-xl aspect-[1.53] w-[173px] max-sm:hidden" />
    <div className="gap-2.5 self-start px-3 py-1 mt-2.5 text-xs uppercase rounded-lg bg-pink-800 bg-opacity-30 min-h-[15px] text-pink-950">
      {location}
    </div>
    <div className="mt-2.5 text-sm">{mealName}</div>
    <div className="flex gap-2 items-center mt-2.5 w-full text-xs rounded-none">
      <div className="flex-1 shrink self-stretch my-auto w-full bg-white">
        Calories: {calories}
      </div>
    </div>
  </div>
);

interface MealCardsProps {}

const MealCards: React.FC<MealCardsProps> = () => {
  const meals = [
    { imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/20d36bff7160213033220e960dab72fcc3d1b1c8fd48ae8bf86e343a98e88456?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8", location: "Worcester Commons", mealName: "Shoyu Ramen", calories: 450 },
    { imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/e0ad73c4e729049df6fadcd642eba4906d13c2f32cbba1d1db5f05d9473dc49b?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8", location: "Worcester Commons", mealName: "Shoyu Ramen", calories: 450 },
    { imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/20d36bff7160213033220e960dab72fcc3d1b1c8fd48ae8bf86e343a98e88456?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8", location: "Worcester Commons", mealName: "Shoyu Ramen", calories: 450 },
  ];

  return (
    <section className="flex flex-col mt-6 w-full max-md:max-w-full max-sm:hidden">
      <div className="flex flex-wrap justify-between w-full max-md:max-w-full">
        <div className="flex gap-3 items-center my-auto">
          <button className="flex gap-2.5 justify-center self-stretch p-1.5 my-auto w-6 border border-solid border-neutral-400 min-h-[24px] rounded-[50px]">
            <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/276d3f106a24b9467c68d5827a4ca135f10d3a84a1a66251d7bd1df4f182fc20?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8" alt="Previous" className="object-contain flex-1 shrink w-3 aspect-square basis-0" />
          </button>
          <button className="flex gap-2.5 justify-center self-stretch p-1.5 my-auto w-6 border border-solid border-neutral-400 min-h-[24px] rounded-[50px]">
            <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/5eb261754e03688687c6770b68137cf57f14891f90f0642df4edef7e4ee0b46f?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8" alt="Next" className="object-contain flex-1 shrink w-3 aspect-square basis-0" />
          </button>
        </div>
      </div>
      <div className="flex flex-wrap gap-5 justify-center items-center mt-5 w-full font-medium text-neutral-800 max-md:max-w-full">
        {meals.map((meal, index) => (
          <MealCard key={index} {...meal} />
        ))}
        <div className="flex flex-col flex-1 shrink justify-center self-stretch px-8 py-11 my-auto text-sm text-center bg-white rounded-3xl shadow-2xl basis-0 max-md:px-5 max-sm:hidden">
          <div className="flex flex-col justify-center min-h-[121px]">
            <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/8a477ecb4133eb593bab2f1a3e213a2a37ccaa1f51bffb0a512009382043620f?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8" alt="Add meal" className="object-contain self-center w-24 rounded-xl aspect-[1.02]" />
            <div className="mt-2.5">Add Meal</div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default MealCards;