/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface NutrientCardProps {
  imageSrc: string;
  altText: string;
  nutrientName: string;
}

const NutrientCard: React.FC<NutrientCardProps> = ({ imageSrc, altText, nutrientName }) => (
  <div className="flex flex-col flex-1 shrink justify-center items-center self-stretch px-3 py-3.5 my-auto bg-white rounded-xl shadow-2xl basis-0 min-h-[124px] min-w-[240px] max-sm:hidden">
    <img loading="lazy" src={imageSrc} alt={altText} className="object-contain w-16 aspect-square max-sm:hidden" />
    <div className="mt-4">{nutrientName}</div>
  </div>
);

interface NutrientCardsProps {}

const NutrientCards: React.FC<NutrientCardsProps> = () => {
  const nutrients = [
    { imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/fa8b9c1f16431edad99b57aae64a8b19f679e7c957c7a9de249c15f25830278b?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8", altText: "Carbs icon", nutrientName: "Carbs" },
    { imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/9656f03fc17c5b6677c425da05334938ae2b33626454df9981bb5887cd4f7500?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8", altText: "Protein icon", nutrientName: "Protein" },
    { imageSrc: "https://cdn.builder.io/api/v1/image/assets/TEMP/b4837d4012287b4951cd75da23d0d57157fe77e3c595dbad98cb03f7a3de5ab9?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8", altText: "Fat icon", nutrientName: "Fat" },
  ];

  return (
    <div className="flex flex-wrap gap-3.5 justify-center items-center mt-6 w-full text-xs font-semibold whitespace-nowrap h-[110px] text-neutral-800 max-md:max-w-full max-sm:hidden">
      {nutrients.map((nutrient, index) => (
        <NutrientCard key={index} {...nutrient} />
      ))}
    </div>
  );
};

export default NutrientCards;