/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import WeekGraph from './WeekGraph';
import SuggestedMeals from './SuggestedMeals';

interface RightSidebarProps {}

const RightSidebar: React.FC<RightSidebarProps> = () => {
  return (
    <aside className="flex flex-col ml-5 w-[22%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col px-6 pt-8 pb-80 mx-auto w-full bg-white rounded-none shadow-2xl min-h-[1227px] max-md:px-5 max-md:pb-24 max-md:mt-8 max-sm:hidden">
        <WeekGraph />
        <SuggestedMeals />
      </div>
    </aside>
  );
};

export default RightSidebar;