/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface SidebarProps {}

const Sidebar: React.FC<SidebarProps> = () => {
  return (
    <nav className="flex flex-col w-[17%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow justify-between items-center p-8 w-full text-base bg-white rounded-3xl shadow-2xl min-h-[933px] max-md:px-5 max-md:mt-8 max-sm:min-h-[1198px]">
        <div className="flex flex-col max-w-full w-[146px]">
          <div className="flex flex-col w-full">
            <h2 className="flex-1 shrink gap-2.5 self-stretch py-2 w-full font-semibold uppercase whitespace-nowrap text-neutral-700">
              OVERVIEW
            </h2>
            <ul className="flex flex-col justify-center mt-2.5 w-full font-medium text-neutral-800">
              <li>
                <a href="#" className="flex gap-3 items-center py-2 w-full text-red-500 whitespace-nowrap bg-white rounded-[40px]">
                  <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/70d9f711a85efdc446cb6fa52770d98d94d17a87b2ec47e20c3b5aa74115eb01?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8" alt="" className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square" />
                  <span className="flex-1 shrink self-stretch my-auto basis-0">Dashboard</span>
                </a>
              </li>
              <li>
                <a href="#" className="flex gap-3 items-center py-2 mt-2 w-full rounded-[40px]">
                  <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/3cf6911b5ca0e2d848eb3b69275e27a356d2c4ee83f135382b151e42f108dbc8?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8" alt="" className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square" />
                  <span className="flex-1 shrink self-stretch my-auto basis-0">Food Log</span>
                </a>
              </li>
              <li>
                <a href="#" className="flex gap-3 items-center py-2 mt-2 w-full whitespace-nowrap rounded-[40px]">
                  <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/1e28313e33f46ac39b6e314674ebc3f164bb1233abad41fd87d09d301b0ceb08?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8" alt="" className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square" />
                  <span className="flex-1 shrink self-stretch my-auto basis-0">Meals</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div className="flex flex-col max-w-full font-medium whitespace-nowrap mt-[578px] w-[146px] max-md:mt-10">
          <h2 className="flex-1 shrink gap-2.5 self-stretch py-2 w-full font-semibold uppercase text-neutral-700">
            SETTINGS
          </h2>
          <ul>
            <li>
              <a href="#" className="flex gap-3 items-center py-2 mt-2.5 w-full rounded-[40px] text-neutral-800">
                <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/9a9ac63f44fdf02244f401553ba9b2b69030a955d2e311783e9a3cd25e812ee1?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8" alt="" className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square" />
                <span className="flex-1 shrink self-stretch my-auto basis-0">Settings</span>
              </a>
            </li>
            <li>
              <a href="#" className="flex gap-3 items-center py-2 mt-2.5 w-full text-red-500 rounded-[40px]">
                <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/76778048cbfc17db5ebd509a8f8d8300efbea99bc23886f51e2b0bf39d43c128?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8" alt="" className="object-contain shrink-0 self-stretch my-auto w-4 aspect-square" />
                <span className="flex-1 shrink self-stretch my-auto basis-0">Logout</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  );
};

export default Sidebar;