/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface UserProfileProps {}

const UserProfile: React.FC<UserProfileProps> = () => {
  return (
    <section className="overflow-hidden px-20 py-5 w-full bg-red-900 rounded-3xl max-md:px-5 max-md:max-w-full max-sm:hidden">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex gap-2.5 items-center p-2.5 max-md:mt-10">
            <div className="flex flex-col justify-center self-stretch p-2.5 my-auto w-[203px]">
              <div className="flex flex-col justify-center p-2.5 w-full">
                <div className="flex flex-col justify-center p-2.5 w-full">
                  <div className="flex flex-col justify-center items-center w-full h-[143px]">
                    <div className="flex justify-center items-center w-full h-[200px]">
                      <img loading="lazy" src="https://cdn.builder.io/api/v1/image/assets/TEMP/b778edba74056af94b24e15b06b50a3fdb7a590bb49ecbb5bd8ee057abed2506?placeholderIfAbsent=true&apiKey=3c3e08ceeec64dce8693bb87026868e8" alt="User profile" className="object-contain self-stretch my-auto aspect-square w-[200px]" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col self-stretch my-auto max-md:mt-10">
            <div className="flex flex-col pl-2.5 text-white">
              <span className="self-start text-xs uppercase">Welcome King</span>
              <h1 className="mt-6 text-2xl font-semibold">Jonathan Zhang</h1>
            </div>
            <div className="flex flex-col justify-center p-2.5 mt-1.5 max-w-full text-right text-red-900 w-[133px]">
              <div className="flex gap-3 items-center py-2 pr-3 pl-4 w-full bg-zinc-300 min-h-[37px] rounded-[40px]">
                <span className="self-stretch my-auto text-xl font-bold">1</span>
                <span className="self-stretch my-auto text-xs font-semibold">Day Streak</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default UserProfile;